<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" />
	<PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
	<PackageReference Include="NUnit.Analyzers" />
	<PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaperlessModels\PaperlessModels.csproj" />
    <ProjectReference Include="..\PaperlessREST\PaperlessREST.csproj" />

  </ItemGroup>

</Project>
