<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OcrWorker-edd414eb-7534-4cbd-8421-beeeaadf4cd5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Minio" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Tesseract" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PaperlessModels\PaperlessModels.csproj" />
  </ItemGroup>

</Project>
