# .github/workflows/ci.yml
name: .NET CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build-test-lint:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check .NET code formatting (Linting)
        run: dotnet format --verify-no-changes --verbosity detailed DocumentManagementSystem.sln

      - name: Restore dependencies
        run: dotnet restore DocumentManagementSystem.sln

      - name: Build
        run: dotnet build DocumentManagementSystem.sln --no-restore

      - name: Test
        run: dotnet test DocumentManagementSystem.sln --no-build --verbosity normal
